// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmtfbnspavxjdyievhwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdGZibnNwYXZ4amR5aWV2aHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDQ0MjAsImV4cCI6MjA2NTQ4MDQyMH0.D_X-FH4oIq9Ue_jQDliMgJ14RwPrpqXbixU3q0tP5u8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);